### PR TITLE
Updated jwt gem and allow jwt options hash to be used

### PR DESCRIPTION
**Pull request by grempe**
Here is a group of commits to enhance the tool and clean up a couple of issues.

The main things addressed are:

* upgrade to security and bugfix upgrade of JWT gem
* allow passing through the options hash that the JWT gem requires in order to verify most claims.

I also pulled in the other pull request that was pending into this group of commits so you only need to do one merge to get both pull requests.

Tests have been added for all changes.

Cheers,

Glenn

### CODE REVIEW

**Comment by grempe** [comment]
cc: @fgehrm

**Comment by grempe** [comment]
PS - A new release once this is pulled in would be great!  Thx.

**Comment by eigenbart** [comment]
@grempe  can't merge your changes :cry:

**Comment by grempe** [comment]
Closing this pull request.  I'll give you another in a minute that does not contain the final commit (which was a reproduction of the other pull request you pulled in, that's why you could no longer merge.  I thought I was making it easier for you to pull just one, but I guess not.

**Pull request closed without merging**
